local rex_pcre = require "rex_pcre"

sourcetype = 'access_combined'
local full_props = {}

full_props['catalina'] = {}

full_props['catalina']['category'] = 'Application'

full_props['catalina']['description'] = 'Output produced by Apache Tomcat Catalina (System.out and System.err)'

full_props['catalina']['BREAK_ONLY_BEFORE_DATE'] = 'true'

full_props['catalina']['pulldown_type'] = '1'

full_props['catalina']['TIME_PREFIX'] = '^'

full_props['catalina']['MAX_TIMESTAMP_LOOKAHEAD'] = '30'

full_props['catalina']['SHOULD_LINEMERGE'] = 'true'


full_props['backup_file'] = {}

full_props['backup_file']['MAX_EVENTS'] = '10000'

full_props['backup_file']['BREAK_ONLY_BEFORE'] = 'goblygook'

full_props['backup_file']['LEARN_MODEL'] = 'false'


full_props['source::.../var/log/splunk/(web|report)_service(-\\d+)?.log(.\\d+)?'] = {}

full_props['source::.../var/log/splunk/(web|report)_service(-\\d+)?.log(.\\d+)?']['sourcetype'] = 'splunk_web_service'


full_props['breakable_text'] = {}

full_props['breakable_text']['BREAK_ONLY_BEFORE'] = '(^(?:---|===|\\*\\*\\*|___|=+=))|^\\s*$'

full_props['breakable_text']['LEARN_MODEL'] = 'false'


full_props['source::.../splunkd.log(.\\d+)?'] = {}

full_props['source::.../splunkd.log(.\\d+)?']['sourcetype'] = 'splunkd'


full_props['source::.../token_input_metrics.log(.\\d+)?'] = {}

full_props['source::.../token_input_metrics.log(.\\d+)?']['sourcetype'] = 'token_endpoint_metrics'


full_props['tcp'] = {}

full_props['tcp']['KV_MODE'] = 'none'

full_props['tcp']['BREAK_ONLY_BEFORE'] = '(=\\+)+'

full_props['tcp']['REPORT-tcp'] = '(?:(\\d+\\.\\d+\\.\\d+\\.\\d+):(\\d+) -> (\\d+\\.\\d+\\.\\d+\\.\\d+):(\\d+))(?<= )([A-Za-z]+): ?((0x[A-F\\d]+)|\\d+)(?= |\\n|$)'

full_props['tcp']['namegroup-REPORT'] = ''


full_props['source::.../var/log/boot.log(.\\d+)?'] = {}

full_props['source::.../var/log/boot.log(.\\d+)?']['sourcetype'] = 'linux_bootlog'


full_props['db2_diag'] = {}

full_props['db2_diag']['category'] = 'Database'

full_props['db2_diag']['maxDist'] = '90'

full_props['db2_diag']['description'] = 'Diagnostic output produced by the IBM DB2 database server'

full_props['db2_diag']['pulldown_type'] = '1'

full_props['db2_diag']['namegroup-REPORT'] = ''

full_props['db2_diag']['REPORT-st'] = '(?:([A-Z]+) *: (.*?)(?=\\n|$| +[A-Z]+ *:))'


full_props['source::.../var/log/dmesg(.\\d+)?'] = {}

full_props['source::.../var/log/dmesg(.\\d+)?']['sourcetype'] = 'dmesg'


full_props['splunk_directory_monitor'] = {}

full_props['splunk_directory_monitor']['MAX_TIMESTAMP_LOOKAHEAD'] = '40'


full_props['cups_access'] = {}

full_props['cups_access']['BREAK_ONLY_BEFORE_DATE'] = 'False'


full_props['preprocess-bzip'] = {}

full_props['preprocess-bzip']['invalid_cause'] = 'archive'

full_props['preprocess-bzip']['is_valid'] = 'False'

full_props['preprocess-bzip']['LEARN_MODEL'] = 'false'


full_props['source::.../var/log/splunk/searches.log'] = {}

full_props['source::.../var/log/splunk/searches.log']['sourcetype'] = 'searches'


full_props['web'] = {}

full_props['web']['MAX_EVENTS'] = '200000'

full_props['web']['BREAK_ONLY_BEFORE'] = 'goblygook'

full_props['web']['LEARN_MODEL'] = 'false'

full_props['web']['CHECK_METHOD'] = 'modtime'

full_props['web']['DATETIME_CONFIG'] = 'NONE'


full_props['manpage'] = {}

full_props['manpage']['MAX_EVENTS'] = '200000'

full_props['manpage']['BREAK_ONLY_BEFORE'] = 'gooblygook'

full_props['manpage']['LEARN_MODEL'] = 'false'

full_props['manpage']['CHECK_METHOD'] = 'modtime'

full_props['manpage']['DATETIME_CONFIG'] = 'NONE'


full_props['fs_notification'] = {}

full_props['fs_notification']['SHOULD_LINEMERGE'] = 'false'


full_props['preprocess-Z'] = {}

full_props['preprocess-Z']['invalid_cause'] = 'archive'

full_props['preprocess-Z']['is_valid'] = 'False'

full_props['preprocess-Z']['LEARN_MODEL'] = 'false'


full_props['access_combined'] = {}

full_props['access_combined']['category'] = 'Web'

full_props['access_combined']['maxDist'] = '28'

full_props['access_combined']['REPORT-access'] = '(?:^(?<clientip>(?:\\S+))\\s++(?<ident>(?:\\S+))\\s++(?<user>(?:\\S+))\\s++(?<req_time>(?:\\[(?:[^\\]]*+)\\]))\\s++(?:"\\s*+(?<method>(?:[^\\s"]++))?(?:\\s++(?<uri>(?<uri_>(?<domain0>\\w++:\\/\\/[^\\/\\s"]++))?+(?<uri_path>(?:\\/++(?<root>(?:\\\\"|[^\\s\\?\\/"])++)\\/++)?(?:(?:\\\\"|[^\\s\\?\\/"])*+\\/++)*(?<file>[^\\s\\?\\/]+)?)(?:\\?(?<uri_query>[^\\s]*))?)(?:\\s++(?<version>(?:[^\\s"]++)))*)?\\s*+")\\s++(?<status>(?:\\S+))\\s++(?<bytes>(?:\\S+))(?:\\s++"(?<referer>(?<referer_>(?<domain>\\w++:\\/\\/[^\\/\\s"]++))?+[^"]*+)"(?:\\s++(?<useragent>(?:"(?:[^"]*+)"))(?:\\s++(?<cookie>(?:"(?:[^"]*+)")))?+)?+)?(?<other>(?:.*)))'

full_props['access_combined']['description'] = 'National Center for Supercomputing Applications (NCSA) combined format HTTP web server logs (can be generated by apache or other web servers)'

full_props['access_combined']['pulldown_type'] = 'true'

full_props['access_combined']['namegroup-REPORT'] = 'clientip,ident,user,req_time,method,uri,uri_,domain0,uri_path,root,file,uri_query,version,status,bytes,referer,referer_,domain,useragent,cookie,other'

full_props['access_combined']['MAX_TIMESTAMP_LOOKAHEAD'] = '128'

full_props['access_combined']['TIME_PREFIX'] = '\\['

full_props['access_combined']['SHOULD_LINEMERGE'] = 'False'


full_props['_json'] = {}

full_props['_json']['KV_MODE'] = 'none'

full_props['_json']['pulldown_type'] = 'true'

full_props['_json']['category'] = 'Structured'

full_props['_json']['description'] = 'JavaScript Object Notation format. For more information, visit http://json.org/'

full_props['_json']['INDEXED_EXTRACTIONS'] = 'json'


full_props['mysqld_error'] = {}

full_props['mysqld_error']['category'] = 'Database'

full_props['mysqld_error']['maxDist'] = '50'

full_props['mysqld_error']['description'] = 'Errors produced by the MySQL database server'

full_props['mysqld_error']['BREAK_ONLY_BEFORE'] = '^\\d{6}\\s'

full_props['mysqld_error']['pulldown_type'] = '1'

full_props['mysqld_error']['MAX_EVENTS'] = '1024'


full_props['source::...stash_new'] = {}

full_props['source::...stash_new']['sourcetype'] = 'stash_new'


full_props['source::.../var/log/anaconda.log(.\\d+)?'] = {}

full_props['source::.../var/log/anaconda.log(.\\d+)?']['sourcetype'] = 'anaconda'


full_props['source::.../var/log/splunk/django_error.log(.\\d+)?'] = {}

full_props['source::.../var/log/splunk/django_error.log(.\\d+)?']['sourcetype'] = 'django_error'


full_props['wmi'] = {}

full_props['wmi']['SHOULD_LINEMERGE'] = 'false'

full_props['wmi']['LINE_BREAKER'] = '([\\r\\n]+---splunk-wmi-end-of-event---\\r\\n[\\r\\n]*)'

full_props['wmi']['CHARSET'] = 'UTF-8'


full_props['splunkd_misc'] = {}

full_props['splunkd_misc']['MAX_TIMESTAMP_LOOKAHEAD'] = '1'

full_props['splunkd_misc']['SHOULD_LINEMERGE'] = 'False'


full_props['splunkd_ui_access'] = {}

full_props['splunkd_ui_access']['maxDist'] = '28'

full_props['splunkd_ui_access']['REPORT-access'] = '(?:^(?<clientip>(?:\\S+))\\s++(?<ident>(?:\\S+))\\s++(?<user>(?:\\S+))\\s++(?<req_time>(?:\\[(?:[^\\]]*+)\\]))\\s++(?:"\\s*+(?<method>(?:[^\\s"]++))?(?:\\s++(?<uri>(?<uri_>(?<domain0>\\w++:\\/\\/[^\\/\\s"]++))?+(?<uri_path>(?:\\/++(?<root>(?:\\\\"|[^\\s\\?\\/"])++)\\/++)?(?:(?:\\\\"|[^\\s\\?\\/"])*+\\/++)*(?<file>[^\\s\\?\\/]+)?)(?:\\?(?<uri_query>[^\\s]*))?)(?:\\s++(?<version>(?:[^\\s"]++)))*)?\\s*+")\\s++(?<status>(?:\\S+))\\s++(?<bytes>(?:\\S+))(?:\\s++"(?<referer>(?<referer_>(?<domain>\\w++:\\/\\/[^\\/\\s"]++))?+[^"]*+)"(?:\\s++(?<useragent>(?:"(?:[^"]*+)"))(?:\\s++(?<cookie>(?:"(?:[^"]*+)")))?+)?+)?(?<other>(?:.*)))(?:(?P<spent>\\d+)ms$)'

full_props['splunkd_ui_access']['MAX_TIMESTAMP_LOOKAHEAD'] = '128'

full_props['splunkd_ui_access']['TIME_PREFIX'] = '\\['

full_props['splunkd_ui_access']['namegroup-REPORT'] = 'clientip,ident,user,req_time,method,uri,uri_,domain0,uri_path,root,file,uri_query,version,status,bytes,referer,referer_,domain,useragent,cookie,other'

full_props['splunkd_ui_access']['SHOULD_LINEMERGE'] = 'False'


full_props['apache_error'] = {}

full_props['apache_error']['category'] = 'Web'

full_props['apache_error']['maxDist'] = '50'

full_props['apache_error']['description'] = 'Error log format produced by the Apache web server (typically error_log on *nix systems)'

full_props['apache_error']['pulldown_type'] = 'true'

full_props['apache_error']['TIME_FORMAT'] = '[%A %B %d %T %Y]'

full_props['apache_error']['BREAK_ONLY_BEFORE'] = '^\\['

full_props['apache_error']['MAX_TIMESTAMP_LOOKAHEAD'] = '128'


full_props['source::.../private/var/log/system.log(.\\d+)?'] = {}

full_props['source::.../private/var/log/system.log(.\\d+)?']['sourcetype'] = 'syslog'


full_props['token_input_metrics'] = {}

full_props['token_input_metrics']['TIME_FORMAT'] = '%m-%d-%Y %H:%M:%S.%l %z'

full_props['token_input_metrics']['KV_MODE'] = 'none'

full_props['token_input_metrics']['SHOULD_LINEMERGE'] = 'false'

full_props['token_input_metrics']['TIMESTAMP_FIELDS'] = 'datetime'

full_props['token_input_metrics']['INDEXED_EXTRACTIONS'] = 'json'


full_props['source::...((.(bak|old))|,v|~|#)'] = {}

full_props['source::...((.(bak|old))|,v|~|#)']['sourcetype'] = 'ignored_type'


full_props['osx_crashreporter'] = {}

full_props['osx_crashreporter']['BREAK_ONLY_BEFORE_DATE'] = 'False'


full_props['source::.../(readme|README)...'] = {}

full_props['source::.../(readme|README)...']['sourcetype'] = 'misc_text'


full_props['source::.../var/log/splunk/scheduler.log(.\\d+)?'] = {}

full_props['source::.../var/log/splunk/scheduler.log(.\\d+)?']['sourcetype'] = 'scheduler'


full_props['source::.../mysql.log(.\\d+)?'] = {}

full_props['source::.../mysql.log(.\\d+)?']['sourcetype'] = 'mysqld'


full_props['source::.../var/log/splunk/searchhistory.log(.\\d+)?'] = {}

full_props['source::.../var/log/splunk/searchhistory.log(.\\d+)?']['namegroup-TRANSFORMS'] = ''

full_props['source::.../var/log/splunk/searchhistory.log(.\\d+)?']['TRANSFORMS'] = '(?:.)'

full_props['source::.../var/log/splunk/searchhistory.log(.\\d+)?']['sourcetype'] = 'splunk_search_history'


full_props['exim_main'] = {}

full_props['exim_main']['SHOULD_LINEMERGE'] = 'False'


full_props['novell_groupwise'] = {}

full_props['novell_groupwise']['MAX_TIMESTAMP_LOOKAHEAD'] = '9'

full_props['novell_groupwise']['SHOULD_LINEMERGE'] = 'False'

full_props['novell_groupwise']['namegroup-TRANSFORMS'] = ''

full_props['novell_groupwise']['TRANSFORMS-nov'] = '(?:ARR ([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),(.*)$)(?:QUE ([^,]*),([^,]*),([^,]*),(.*)$)(?:QUE ([^,]*),([^,]*),([^,]*),([^,]*)$)'


full_props['linux_secure'] = {}

full_props['linux_secure']['category'] = 'Operating System'

full_props['linux_secure']['description'] = 'Format for the /var/log/secure file containing all security related messages on a Linux machine'

full_props['linux_secure']['pulldown_type'] = '1'

full_props['linux_secure']['REPORT-syslog'] = '(?:\\s([^\\s\\[]+)(?:\\[(\\d+)\\])?:\\s)'

full_props['linux_secure']['namegroup-REPORT'] = ''

full_props['linux_secure']['SHOULD_LINEMERGE'] = 'False'


full_props['source::.../var/log/splunk/django_service.log(.\\d+)?'] = {}

full_props['source::.../var/log/splunk/django_service.log(.\\d+)?']['sourcetype'] = 'django_service'


full_props['anaconda_syslog'] = {}

full_props['anaconda_syslog']['TIME_FORMAT'] = '%b %d %H:%M:%S'

full_props['anaconda_syslog']['REPORT-syslog'] = '(?:\\s([^\\s\\[]+)(?:\\[(\\d+)\\])?:\\s)'

full_props['anaconda_syslog']['SHOULD_LINEMERGE'] = 'False'

full_props['anaconda_syslog']['namegroup-REPORT'] = ''


full_props['psv'] = {}

full_props['psv']['KV_MODE'] = 'none'

full_props['psv']['category'] = 'Structured'

full_props['psv']['description'] = 'Pipe-separated value format. Set header and other settings in "Delimited Settings"'

full_props['psv']['FIELD_DELIMITER'] = '|'

full_props['psv']['INDEXED_EXTRACTIONS'] = 'psv'

full_props['psv']['pulldown_type'] = 'true'

full_props['psv']['SHOULD_LINEMERGE'] = 'False'

full_props['psv']['HEADER_FIELD_DELIMITER'] = '|'


full_props['(?i)source::....zip(.\\d+)?'] = {}

full_props['(?i)source::....zip(.\\d+)?']['unarchive_cmd'] = '_auto'

full_props['(?i)source::....zip(.\\d+)?']['sourcetype'] = 'preprocess-zip'

full_props['(?i)source::....zip(.\\d+)?']['NO_BINARY_CHECK'] = 'true'


full_props['django_access'] = {}

full_props['django_access']['maxDist'] = '28'

full_props['django_access']['REPORT-access'] = '(?:^(?<clientip>(?:\\S+))\\s++(?<ident>(?:\\S+))\\s++(?<user>(?:\\S+))\\s++(?<req_time>(?:\\[(?:[^\\]]*+)\\]))\\s++(?:"\\s*+(?<method>(?:[^\\s"]++))?(?:\\s++(?<uri>(?<uri_>(?<domain0>\\w++:\\/\\/[^\\/\\s"]++))?+(?<uri_path>(?:\\/++(?<root>(?:\\\\"|[^\\s\\?\\/"])++)\\/++)?(?:(?:\\\\"|[^\\s\\?\\/"])*+\\/++)*(?<file>[^\\s\\?\\/]+)?)(?:\\?(?<uri_query>[^\\s]*))?)(?:\\s++(?<version>(?:[^\\s"]++)))*)?\\s*+")\\s++(?<status>(?:\\S+))\\s++(?<bytes>(?:\\S+))(?:\\s++"(?<referer>(?<referer_>(?<domain>\\w++:\\/\\/[^\\/\\s"]++))?+[^"]*+)"(?:\\s++(?<useragent>(?:"(?:[^"]*+)"))(?:\\s++(?<cookie>(?:"(?:[^"]*+)")))?+)?+)?(?<other>(?:.*)))'

full_props['django_access']['EXTRACT-extract_spent'] = '(?<spent>\\d+)ms$'

full_props['django_access']['namegroup-REPORT'] = 'clientip,ident,user,req_time,method,uri,uri_,domain0,uri_path,root,file,uri_query,version,status,bytes,referer,referer_,domain,useragent,cookie,other'

full_props['django_access']['MAX_TIMESTAMP_LOOKAHEAD'] = '128'

full_props['django_access']['TIME_PREFIX'] = '\\['

full_props['django_access']['SHOULD_LINEMERGE'] = 'False'


full_props['osx_crash_log'] = {}

full_props['osx_crash_log']['MAX_EVENTS'] = '200000'

full_props['osx_crash_log']['BREAK_ONLY_BEFORE'] = 'gooblygook'


full_props['source_archive'] = {}

full_props['source_archive']['invalid_cause'] = 'needs_preprocess'

full_props['source_archive']['is_valid'] = 'False'

full_props['source_archive']['LEARN_MODEL'] = 'false'


full_props['source::.../var/log/splunk/mongod.log(.\\d+)?'] = {}

full_props['source::.../var/log/splunk/mongod.log(.\\d+)?']['sourcetype'] = 'mongod'


full_props['source::.../var/log/splunk/intentions.log(.\\d+)?'] = {}

full_props['source::.../var/log/splunk/intentions.log(.\\d+)?']['sourcetype'] = 'splunk_intentions'


full_props['wtmp'] = {}

full_props['wtmp']['invalid_cause'] = 'binary'

full_props['wtmp']['LEARN_MODEL'] = 'false'


full_props['websphere_core'] = {}

full_props['websphere_core']['category'] = 'Application'

full_props['websphere_core']['pulldown_type'] = 'true'

full_props['websphere_core']['BREAK_ONLY_BEFORE'] = '^NULL\\s'

full_props['websphere_core']['description'] = 'Output produced by the IBM WebSphere application server'

full_props['websphere_core']['maxDist'] = '70'


full_props['source::....(0t|a|ali|asa|au|bmp|cg|cgi|class|d|dat|deb|del|dot|dvi|dylib|elc|eps|exe|ftn|gif|hlp|hqx|hs|icns|ico|inc|iso|jame|jin|jpeg|jpg|kml|la|lhs|lib|lo|lock|mcp|mid|mp3|mpg|msf|nib|o|obj|odt|ogg|ook|opt|os|pal|pbm|pdf|pem|pgm|plo|png|po|pod|pp|ppd|ppm|ppt|prc|ps|psd|psym|pyc|pyd|rast|rb|rde|rdf|rdr|rgb|ro|rpm|rsrc|so|ss|stg|strings|tdt|tif|tiff|tk|uue|vhd|xbm|xlb|xls|xlw)'] = {}

full_props['source::....(0t|a|ali|asa|au|bmp|cg|cgi|class|d|dat|deb|del|dot|dvi|dylib|elc|eps|exe|ftn|gif|hlp|hqx|hs|icns|ico|inc|iso|jame|jin|jpeg|jpg|kml|la|lhs|lib|lo|lock|mcp|mid|mp3|mpg|msf|nib|o|obj|odt|ogg|ook|opt|os|pal|pbm|pdf|pem|pgm|plo|png|po|pod|pp|ppd|ppm|ppt|prc|ps|psd|psym|pyc|pyd|rast|rb|rde|rdf|rdr|rgb|ro|rpm|rsrc|so|ss|stg|strings|tdt|tif|tiff|tk|uue|vhd|xbm|xlb|xls|xlw)']['sourcetype'] = 'known_binary'


full_props['websphere_activity'] = {}

full_props['websphere_activity']['category'] = 'Application'

full_props['websphere_activity']['description'] = 'Activity logs produced by the Oracle WebLogic Java EE application server'

full_props['websphere_activity']['BREAK_ONLY_BEFORE'] = '^-----'

full_props['websphere_activity']['pulldown_type'] = 'true'

full_props['websphere_activity']['namegroup-REPORT'] = ''

full_props['websphere_activity']['MAX_TIMESTAMP_LOOKAHEAD'] = '500'

full_props['websphere_activity']['REPORT-st'] = '(?:^(\\w+)\\s*:[ \\t]*(.*?)$)'


full_props['source::WinEventLog...'] = {}

full_props['source::WinEventLog...']['KV_MODE'] = 'none'

full_props['source::WinEventLog...']['TRANSFORMS-FIELDS'] = '(?:(?s)^(.*)---splunk-wevt-end-of-event---)'

full_props['source::WinEventLog...']['REPORT-MESSAGE'] = '(?:(?sm)^(?<_pre_msg>.+)\\nMessage=(?<Message>.+)$)(?:\\n([^:\\n\\r]+):[ \\t]++([^\\n]*))'

full_props['source::WinEventLog...']['namegroup-REPORT'] = '_pre_msg,Message'

full_props['source::WinEventLog...']['MAX_TIMESTAMP_LOOKAHEAD'] = '30'

full_props['source::WinEventLog...']['SHOULD_LINEMERGE'] = 'false'

full_props['source::WinEventLog...']['LINE_BREAKER'] = '([\\r\\n](?=\\d{2}/\\d{2}/\\d{2,4} \\d{2}:\\d{2}:\\d{2} [aApPmM]{2}))'

full_props['source::WinEventLog...']['namegroup-TRANSFORMS'] = ''


full_props['snort'] = {}

full_props['snort']['KV_MODE'] = 'none'

full_props['snort']['category'] = 'Network & Security'

full_props['snort']['description'] = 'Output produced by the Snort network intrusion detection/prevention application'

full_props['snort']['BREAK_ONLY_BEFORE'] = '(=\\+)+'

full_props['snort']['REPORT-tcp'] = '(?:(\\d+\\.\\d+\\.\\d+\\.\\d+):(\\d+) -> (\\d+\\.\\d+\\.\\d+\\.\\d+):(\\d+))(?<= )([A-Za-z]+): ?((0x[A-F\\d]+)|\\d+)(?= |\\n|$)'

full_props['snort']['pulldown_type'] = 'true'

full_props['snort']['namegroup-REPORT'] = ''


full_props['source::....(cache|class|cxx|dylib|jar|lo|xslt|md5|rpm|deb|iso|vim)'] = {}

full_props['source::....(cache|class|cxx|dylib|jar|lo|xslt|md5|rpm|deb|iso|vim)']['sourcetype'] = 'ignored_type'


full_props['access_common'] = {}

full_props['access_common']['MAX_TIMESTAMP_LOOKAHEAD'] = '128'

full_props['access_common']['SHOULD_LINEMERGE'] = 'False'

full_props['access_common']['namegroup-REPORT'] = 'clientip,ident,user,req_time,method,uri,uri_,domain0,uri_path,root,file,uri_query,version,status,bytes,referer,referer_,domain,useragent,cookie,other'

full_props['access_common']['REPORT-access'] = '(?:^(?<clientip>(?:\\S+))\\s++(?<ident>(?:\\S+))\\s++(?<user>(?:\\S+))\\s++(?<req_time>(?:\\[(?:[^\\]]*+)\\]))\\s++(?:"\\s*+(?<method>(?:[^\\s"]++))?(?:\\s++(?<uri>(?<uri_>(?<domain0>\\w++:\\/\\/[^\\/\\s"]++))?+(?<uri_path>(?:\\/++(?<root>(?:\\\\"|[^\\s\\?\\/"])++)\\/++)?(?:(?:\\\\"|[^\\s\\?\\/"])*+\\/++)*(?<file>[^\\s\\?\\/]+)?)(?:\\?(?<uri_query>[^\\s]*))?)(?:\\s++(?<version>(?:[^\\s"]++)))*)?\\s*+")\\s++(?<status>(?:\\S+))\\s++(?<bytes>(?:\\S+))(?:\\s++"(?<referer>(?<referer_>(?<domain>\\w++:\\/\\/[^\\/\\s"]++))?+[^"]*+)"(?:\\s++(?<useragent>(?:"(?:[^"]*+)"))(?:\\s++(?<cookie>(?:"(?:[^"]*+)")))?+)?+)?(?<other>(?:.*)))'

full_props['access_common']['TIME_PREFIX'] = '\\['


full_props['log4net_xml'] = {}

full_props['log4net_xml']['category'] = 'Application'

full_props['log4net_xml']['maxDist'] = '75'

full_props['log4net_xml']['description'] = 'An XML-formatted output of the Apache log4j framework to the Microsoft .NET runtime'

full_props['log4net_xml']['pulldown_type'] = '1'

full_props['log4net_xml']['BREAK_ONLY_BEFORE'] = '<log4net:event'

full_props['log4net_xml']['NO_BINARY_CHECK'] = '1'

full_props['log4net_xml']['MAX_EVENTS'] = '1000'

full_props['log4net_xml']['TIME_PREFIX'] = 'timestamp="'

full_props['log4net_xml']['SHOULD_LINEMERGE'] = 'true'


full_props['clavister'] = {}

full_props['clavister']['SHOULD_LINEMERGE'] = 'False'


full_props['asterisk_cdr'] = {}

full_props['asterisk_cdr']['MAX_TIMESTAMP_LOOKAHEAD'] = '256'

full_props['asterisk_cdr']['SHOULD_LINEMERGE'] = 'False'


full_props['splunkd_stderr'] = {}

full_props['splunkd_stderr']['TIME_FORMAT'] = '%m-%d-%Y %T.%Q %z'

full_props['splunkd_stderr']['MAX_TIMESTAMP_LOOKAHEAD'] = '40'

full_props['splunkd_stderr']['SHOULD_LINEMERGE'] = 'False'


full_props['rule::exim_main'] = {}

full_props['rule::exim_main']['MORE_THANA_2'] = '<='

full_props['rule::exim_main']['MORE_THANB_2'] = '=>'

full_props['rule::exim_main']['sourcetype'] = 'exim_main'

full_props['rule::exim_main']['MORE_THANC_2'] = 'queue'


full_props['source::WMI...'] = {}

full_props['source::WMI...']['namegroup-REPORT'] = '_pre_msg,Message'

full_props['source::WMI...']['REPORT-MESSAGE'] = '(?:(?sm)^(?<_pre_msg>.+)\\nMessage=(?<Message>.+)$)(?:\\n([^:\\n\\r]+):[ \\t]++([^\\n]*))'

full_props['source::WMI...']['namegroup-TRANSFORMS'] = ''

full_props['source::WMI...']['SHOULD_LINEMERGE'] = 'false'

full_props['source::WMI...']['TRANSFORMS-FIELDS'] = '(?m)ComputerName=(.+)(?m)wmi_hostname=(.+)'


full_props['windows_snare_syslog'] = {}

full_props['windows_snare_syslog']['category'] = 'Operating System'

full_props['windows_snare_syslog']['description'] = 'Output produced by the Snare syslog server on Windows'

full_props['windows_snare_syslog']['TIME_FORMAT'] = '%b %d %H:%M:%S'

full_props['windows_snare_syslog']['pulldown_type'] = '1'

full_props['windows_snare_syslog']['namegroup-REPORT'] = ''

full_props['windows_snare_syslog']['TRANSFORMS'] = '(?::\\d\\d\\s+(?:\\d+\\s+|(?:user|daemon|local.?)\\.\\w+\\s+)*\\[?(\\w[\\w\\.\\-]{2,})\\]?\\s)'

full_props['windows_snare_syslog']['MAX_TIMESTAMP_LOOKAHEAD'] = '32'

full_props['windows_snare_syslog']['REPORT-syslog'] = '(?:\\s([^\\s\\[]+)(?:\\[(\\d+)\\])?:\\s)'

full_props['windows_snare_syslog']['SHOULD_LINEMERGE'] = 'False'

full_props['windows_snare_syslog']['namegroup-TRANSFORMS'] = ''


full_props['json_no_timestamp'] = {}

full_props['json_no_timestamp']['category'] = 'Structured'

full_props['json_no_timestamp']['description'] = 'A variant of the JSON source type, with support for nonexistent timestamps'

full_props['json_no_timestamp']['pulldown_type'] = '1'

full_props['json_no_timestamp']['BREAK_ONLY_BEFORE'] = '^{'

full_props['json_no_timestamp']['DATETIME_CONFIG'] = 'CURRENT'

full_props['json_no_timestamp']['MAX_TIMESTAMP_LOOKAHEAD'] = '800'


full_props['source::.../var/log/cups/access_log(.\\d+)?'] = {}

full_props['source::.../var/log/cups/access_log(.\\d+)?']['sourcetype'] = 'cups_access'


full_props['splunk_resource_usage'] = {}

full_props['splunk_resource_usage']['TIME_FORMAT'] = '%m-%d-%Y %H:%M:%S.%l %z'

full_props['splunk_resource_usage']['KV_MODE'] = 'none'

full_props['splunk_resource_usage']['SHOULD_LINEMERGE'] = 'false'

full_props['splunk_resource_usage']['TIMESTAMP_FIELDS'] = 'datetime'

full_props['splunk_resource_usage']['INDEXED_EXTRACTIONS'] = 'json'


full_props['__singleline'] = {}

full_props['__singleline']['SHOULD_LINEMERGE'] = 'False'


full_props['syslog'] = {}

full_props['syslog']['category'] = 'Operating System'

full_props['syslog']['maxDist'] = '3'

full_props['syslog']['description'] = 'Output produced by many syslog daemons, as described in RFC3164 by the IETF'

full_props['syslog']['TIME_FORMAT'] = '%b %d %H:%M:%S'

full_props['syslog']['pulldown_type'] = 'true'

full_props['syslog']['namegroup-REPORT'] = ''

full_props['syslog']['TRANSFORMS'] = '(?::\\d\\d\\s+(?:\\d+\\s+|(?:user|daemon|local.?)\\.\\w+\\s+)*\\[?(\\w[\\w\\.\\-]{2,})\\]?\\s)'

full_props['syslog']['MAX_TIMESTAMP_LOOKAHEAD'] = '32'

full_props['syslog']['REPORT-syslog'] = '(?:\\s([^\\s\\[]+)(?:\\[(\\d+)\\])?:\\s)'

full_props['syslog']['SHOULD_LINEMERGE'] = 'False'

full_props['syslog']['namegroup-TRANSFORMS'] = ''


full_props['stash_new'] = {}

full_props['stash_new']['MAX_DIFF_SECS_HENCE'] = '155520000'

full_props['stash_new']['LEARN_MODEL'] = 'false'

full_props['stash_new']['MAX_DAYS_HENCE'] = '2'

full_props['stash_new']['TRUNCATE'] = '0'

full_props['stash_new']['TRANSFORMS-sourcetype'] = '(?:.)'

full_props['stash_new']['HEADER_MODE'] = 'firstline'

full_props['stash_new']['BREAK_ONLY_BEFORE_DATE'] = 'false'

full_props['stash_new']['MAX_DAYS_AGO'] = '10000'

full_props['stash_new']['MAX_TIMESTAMP_LOOKAHEAD'] = '64'

full_props['stash_new']['SHOULD_LINEMERGE'] = 'false'

full_props['stash_new']['LINE_BREAKER'] = '(\\r?\\n==##~~##~~  1E8N3D4E6V5E7N2T9 ~~##~~##==\\r?\\n)'

full_props['stash_new']['namegroup-TRANSFORMS'] = ''

full_props['stash_new']['MAX_DIFF_SECS_AGO'] = '155520000'


full_props['anaconda'] = {}

full_props['anaconda']['BREAK_ONLY_BEFORE'] = '^\\*'


full_props['source::.../var/log/splunk/migration.log.*'] = {}

full_props['source::.../var/log/splunk/migration.log.*']['sourcetype'] = 'splunk_migration'


full_props['source::.../var/log/httpd/error_log(.\\d+)?'] = {}

full_props['source::.../var/log/httpd/error_log(.\\d+)?']['sourcetype'] = 'apache_error'


full_props['ftp'] = {}

full_props['ftp']['pulldown_type'] = '0'

full_props['ftp']['BREAK_ONLY_BEFORE_DATE'] = 'False'


full_props['asterisk_messages'] = {}

full_props['asterisk_messages']['SHOULD_LINEMERGE'] = 'False'


full_props['too_small'] = {}

full_props['too_small']['maxDist'] = '9999'

full_props['too_small']['BREAK_ONLY_BEFORE_DATE'] = 'True'

full_props['too_small']['PREFIX_SOURCETYPE'] = 'True'


full_props['mysql_slow'] = {}

full_props['mysql_slow']['category'] = 'Database'

full_props['mysql_slow']['description'] = 'Slow query log output produced by the MySQL database server'

full_props['mysql_slow']['pulldown_type'] = '1'

full_props['mysql_slow']['TIME_FORMAT'] = 'Time: %y%m%d %k:%M:%S %Z'

full_props['mysql_slow']['BREAK_ONLY_BEFORE'] = '#\\sTime:\\s\\d{6}\\s[\\s\\d]\\d:\\d\\d:\\d\\d'

full_props['mysql_slow']['MAX_EVENTS'] = '512'

full_props['mysql_slow']['SHOULD_LINEMERGE'] = 'true'


full_props['splunkd_access'] = {}

full_props['splunkd_access']['maxDist'] = '28'

full_props['splunkd_access']['REPORT-access'] = '(?:^(?<clientip>(?:\\S+))\\s++(?<ident>(?:\\S+))\\s++(?<user>(?:\\S+))\\s++(?<req_time>(?:\\[(?:[^\\]]*+)\\]))\\s++(?:"\\s*+(?<method>(?:[^\\s"]++))?(?:\\s++(?<uri>(?<uri_>(?<domain0>\\w++:\\/\\/[^\\/\\s"]++))?+(?<uri_path>(?:\\/++(?<root>(?:\\\\"|[^\\s\\?\\/"])++)\\/++)?(?:(?:\\\\"|[^\\s\\?\\/"])*+\\/++)*(?<file>[^\\s\\?\\/]+)?)(?:\\?(?<uri_query>[^\\s]*))?)(?:\\s++(?<version>(?:[^\\s"]++)))*)?\\s*+")\\s++(?<status>(?:\\S+))\\s++(?<bytes>(?:\\S+))(?:\\s++"(?<referer>(?<referer_>(?<domain>\\w++:\\/\\/[^\\/\\s"]++))?+[^"]*+)"(?:\\s++(?<useragent>(?:"(?:[^"]*+)"))(?:\\s++(?<cookie>(?:"(?:[^"]*+)")))?+)?+)?(?<other>(?:.*)))(?:(?P<spent>\\d+)ms$)'

full_props['splunkd_access']['MAX_TIMESTAMP_LOOKAHEAD'] = '128'

full_props['splunkd_access']['TIME_PREFIX'] = '\\['

full_props['splunkd_access']['namegroup-REPORT'] = 'clientip,ident,user,req_time,method,uri,uri_,domain0,uri_path,root,file,uri_query,version,status,bytes,referer,referer_,domain,useragent,cookie,other'

full_props['splunkd_access']['SHOULD_LINEMERGE'] = 'False'


full_props['delayedrule::breakable_text'] = {}

full_props['delayedrule::breakable_text']['sourcetype'] = 'breakable_text'

full_props['delayedrule::breakable_text']['MORE_THAN_10'] = '(^(?:---|===|\\*\\*\\*|___|=+=))|^\\s*$'

full_props['delayedrule::breakable_text']['LESS_THAN_10'] = '[: ][012]?[0-9]:[0-5][0-9]'


full_props['linux_messages_syslog'] = {}

full_props['linux_messages_syslog']['category'] = 'Operating System'

full_props['linux_messages_syslog']['description'] = 'Format found within the Linux log file /var/log/messages'

full_props['linux_messages_syslog']['TIME_FORMAT'] = '%b %d %H:%M:%S'

full_props['linux_messages_syslog']['pulldown_type'] = '1'

full_props['linux_messages_syslog']['namegroup-REPORT'] = ''

full_props['linux_messages_syslog']['TRANSFORMS'] = '(?::\\d\\d\\s+(?:\\d+\\s+|(?:user|daemon|local.?)\\.\\w+\\s+)*\\[?(\\w[\\w\\.\\-]{2,})\\]?\\s)'

full_props['linux_messages_syslog']['MAX_TIMESTAMP_LOOKAHEAD'] = '32'

full_props['linux_messages_syslog']['REPORT-syslog'] = '(?:\\s([^\\s\\[]+)(?:\\[(\\d+)\\])?:\\s)'

full_props['linux_messages_syslog']['SHOULD_LINEMERGE'] = 'False'

full_props['linux_messages_syslog']['namegroup-TRANSFORMS'] = ''


full_props['cisco:asa'] = {}

full_props['cisco:asa']['category'] = 'Network & Security'

full_props['cisco:asa']['pulldown_type'] = '1'

full_props['cisco:asa']['SHOULD_LINEMERGE'] = 'false'

full_props['cisco:asa']['description'] = 'Output produced by the Cisco Adaptive Security Appliance (ASA) Firewall'


full_props['source::.../var/log/install.log(.\\d+)?'] = {}

full_props['source::.../var/log/install.log(.\\d+)?']['sourcetype'] = 'osx_install'


full_props['splunk-blocksignature'] = {}

full_props['splunk-blocksignature']['MAX_TIMESTAMP_LOOKAHEAD'] = '40'

full_props['splunk-blocksignature']['SEGMENTATION'] = 'whitespace-only'


full_props['exim_reject'] = {}

full_props['exim_reject']['SHOULD_LINEMERGE'] = 'False'


full_props['splunkd_crash_log'] = {}

full_props['splunkd_crash_log']['MUST_BREAK_AFTER'] = '^(?i)terminating\\.\\.\\.'

full_props['splunkd_crash_log']['MAX_TIMESTAMP_LOOKAHEAD'] = '1'

full_props['splunkd_crash_log']['SHOULD_LINEMERGE'] = 'True'

full_props['splunkd_crash_log']['MAX_EVENTS'] = '2048'

full_props['splunkd_crash_log']['DATETIME_CONFIG'] = 'NONE'


full_props['fileTrackerCrcLog'] = {}

full_props['fileTrackerCrcLog']['KV_MODE'] = 'none'

full_props['fileTrackerCrcLog']['SEGMENTATION'] = 'meta-tokenizer'

full_props['fileTrackerCrcLog']['EXTRACT-1'] = '(?<_KEY_1>\\S+)::(?<_VAL_1>\\S+)'


full_props['linux_audit'] = {}

full_props['linux_audit']['category'] = 'Operating System'

full_props['linux_audit']['pulldown_type'] = '1'

full_props['linux_audit']['BREAK_ONLY_BEFORE_DATE'] = 'False'

full_props['linux_audit']['description'] = 'Output produced by the auditd system daemon used to track changes on a Linux machine'


full_props['splunk_search_history'] = {}

full_props['splunk_search_history']['BREAK_ONLY_BEFORE'] = '^\\d'

full_props['splunk_search_history']['MAX_TIMESTAMP_LOOKAHEAD'] = '40'


full_props['source::.../var/log/splunk/remote_searches.log(.\\d+)?'] = {}

full_props['source::.../var/log/splunk/remote_searches.log(.\\d+)?']['sourcetype'] = 'splunkd_remote_searches'


full_props['source::.../resource_usage.log(.\\d+)?'] = {}

full_props['source::.../resource_usage.log(.\\d+)?']['sourcetype'] = 'splunk_resource_usage'


full_props['source::.../var/log/splunk/python.log(.\\d+)?'] = {}

full_props['source::.../var/log/splunk/python.log(.\\d+)?']['sourcetype'] = 'splunk_python'


full_props['source::.../var/log/weekly.out(.\\d+)?'] = {}

full_props['source::.../var/log/weekly.out(.\\d+)?']['sourcetype'] = 'osx_weekly'


full_props['exchange'] = {}

full_props['exchange']['KV_MODE'] = 'none'

full_props['exchange']['INDEXED_EXTRACTIONS'] = 'w3c'


full_props['source::.../var/log/audit/audit.log(.\\d+)?'] = {}

full_props['source::.../var/log/audit/audit.log(.\\d+)?']['sourcetype'] = 'linux_audit'


full_props['django_service'] = {}

full_props['django_service']['MAX_TIMESTAMP_LOOKAHEAD'] = '40'

full_props['django_service']['TRUNCATE'] = '100000'


full_props['ActiveDirectory'] = {}

full_props['ActiveDirectory']['EXTRACT-SID'] = 'objectSid\\s*=\\s*(?<sid_lookup>\\S+)'

full_props['ActiveDirectory']['TRUNCATE'] = '100000'

full_props['ActiveDirectory']['EXTRACT-GUID'] = '(?i)(?!=\\w)(?:objectguid|guid)\\s*=\\s*(?<guid_lookup>[\\w\\-]+)'

full_props['ActiveDirectory']['REPORT-MESSAGE'] = '(?<_KEY_1>[\\w-]+)=(?<_VAL_1>[^\\r\\n]*)'

full_props['ActiveDirectory']['MAX_EVENTS'] = '10000'

full_props['ActiveDirectory']['namegroup-REPORT'] = '_KEY_1,_VAL_1'

full_props['ActiveDirectory']['SHOULD_LINEMERGE'] = 'false'

full_props['ActiveDirectory']['LINE_BREAKER'] = '([\\r\\n]+---splunk-admon-end-of-event---\\r\\n[\\r\\n]*)'


full_props['procmail'] = {}

full_props['procmail']['category'] = 'Email'

full_props['procmail']['pulldown_type'] = '1'

full_props['procmail']['MAX_TIMESTAMP_LOOKAHEAD'] = '64'

full_props['procmail']['description'] = 'Output produced by the Procmail email server'

full_props['procmail']['BREAK_ONLY_BEFORE'] = 'procmail: \\[\\d+\\]'


full_props['linux_bootlog'] = {}

full_props['linux_bootlog']['BREAK_ONLY_BEFORE_DATE'] = 'False'


full_props['weblogic_stdout'] = {}

full_props['weblogic_stdout']['category'] = 'Application'

full_props['weblogic_stdout']['maxDist'] = '60'

full_props['weblogic_stdout']['description'] = 'Output produced by the Oracle WebLogic Java EE application server'

full_props['weblogic_stdout']['pulldown_type'] = 'true'

full_props['weblogic_stdout']['namegroup-REPORT'] = ''

full_props['weblogic_stdout']['MAX_EVENTS'] = '2048'

full_props['weblogic_stdout']['MAX_TIMESTAMP_LOOKAHEAD'] = '32'

full_props['weblogic_stdout']['REPORT-st'] = '(?:<BEA-([0-9]+)>)'


full_props['mysqld'] = {}

full_props['mysqld']['category'] = 'Database'

full_props['mysqld']['maxDist'] = '20'

full_props['mysqld']['description'] = 'Output produced by the MySQL database server'

full_props['mysqld']['BREAK_ONLY_BEFORE'] = '^\\d{6}\\s'

full_props['mysqld']['TIME_FORMAT'] = '%y%m%d %k:%M:%S'

full_props['mysqld']['pulldown_type'] = '1'


full_props['source::.../var/log/httpd/httpd/ssl_error_log(.\\d+)?'] = {}

full_props['source::.../var/log/httpd/httpd/ssl_error_log(.\\d+)?']['sourcetype'] = 'ssl_error'


full_props['source::.../var/log/sa/sar\\d+'] = {}

full_props['source::.../var/log/sa/sar\\d+']['sourcetype'] = 'sar'


full_props['rpmpkgs'] = {}

full_props['rpmpkgs']['LEARN_MODEL'] = 'false'

full_props['rpmpkgs']['BREAK_ONLY_BEFORE_DATE'] = 'False'


full_props['source::.../var/log/splunk/(license_usage).log(.\\d+)?'] = {}

full_props['source::.../var/log/splunk/(license_usage).log(.\\d+)?']['sourcetype'] = 'splunkd'


full_props['mongod'] = {}

full_props['mongod']['TIME_FORMAT'] = '%Y-%m-%dT%H:%M:%S.%3N%Z'

full_props['mongod']['MAX_TIMESTAMP_LOOKAHEAD'] = '40'

full_props['mongod']['SHOULD_LINEMERGE'] = 'False'


full_props['preprocess-gzip'] = {}

full_props['preprocess-gzip']['invalid_cause'] = 'archive'

full_props['preprocess-gzip']['is_valid'] = 'False'

full_props['preprocess-gzip']['LEARN_MODEL'] = 'false'


full_props['WinWinHostMon'] = {}

full_props['WinWinHostMon']['SHOULD_LINEMERGE'] = 'false'

full_props['WinWinHostMon']['DATETIME_CONFIG'] = 'NONE'


full_props['access_combined_wcookie'] = {}

full_props['access_combined_wcookie']['MAX_TIMESTAMP_LOOKAHEAD'] = '128'

full_props['access_combined_wcookie']['SHOULD_LINEMERGE'] = 'False'

full_props['access_combined_wcookie']['namegroup-REPORT'] = 'clientip,ident,user,req_time,method,uri,uri_,domain0,uri_path,root,file,uri_query,version,status,bytes,referer,referer_,domain,useragent,cookie,other'

full_props['access_combined_wcookie']['REPORT-access'] = '(?:^(?<clientip>(?:\\S+))\\s++(?<ident>(?:\\S+))\\s++(?<user>(?:\\S+))\\s++(?<req_time>(?:\\[(?:[^\\]]*+)\\]))\\s++(?:"\\s*+(?<method>(?:[^\\s"]++))?(?:\\s++(?<uri>(?<uri_>(?<domain0>\\w++:\\/\\/[^\\/\\s"]++))?+(?<uri_path>(?:\\/++(?<root>(?:\\\\"|[^\\s\\?\\/"])++)\\/++)?(?:(?:\\\\"|[^\\s\\?\\/"])*+\\/++)*(?<file>[^\\s\\?\\/]+)?)(?:\\?(?<uri_query>[^\\s]*))?)(?:\\s++(?<version>(?:[^\\s"]++)))*)?\\s*+")\\s++(?<status>(?:\\S+))\\s++(?<bytes>(?:\\S+))(?:\\s++"(?<referer>(?<referer_>(?<domain>\\w++:\\/\\/[^\\/\\s"]++))?+[^"]*+)"(?:\\s++(?<useragent>(?:"(?:[^"]*+)"))(?:\\s++(?<cookie>(?:"(?:[^"]*+)")))?+)?+)?(?<other>(?:.*)))'

full_props['access_combined_wcookie']['TIME_PREFIX'] = '\\['


full_props['source::.../syslog(.\\d+)?'] = {}

full_props['source::.../syslog(.\\d+)?']['sourcetype'] = 'syslog'


full_props['splunk_disk_objects'] = {}

full_props['splunk_disk_objects']['TIME_FORMAT'] = '%m-%d-%Y %H:%M:%S.%l %z'

full_props['splunk_disk_objects']['KV_MODE'] = 'none'

full_props['splunk_disk_objects']['SHOULD_LINEMERGE'] = 'false'

full_props['splunk_disk_objects']['TIMESTAMP_FIELDS'] = 'datetime'

full_props['splunk_disk_objects']['INDEXED_EXTRACTIONS'] = 'json'


full_props['source::.../var/log/monthly.out(.\\d+)?'] = {}

full_props['source::.../var/log/monthly.out(.\\d+)?']['sourcetype'] = 'osx_monthly'


full_props['source::.../var/log/splunk/audit.log(.\\d+)?'] = {}

full_props['source::.../var/log/splunk/audit.log(.\\d+)?']['namegroup-TRANSFORMS'] = ''

full_props['source::.../var/log/splunk/audit.log(.\\d+)?']['TRANSFORMS'] = '(?:.)'

full_props['source::.../var/log/splunk/audit.log(.\\d+)?']['sourcetype'] = 'splunk_audit'


full_props['source::.../var/log/asl.log(.\\d+)?'] = {}

full_props['source::.../var/log/asl.log(.\\d+)?']['sourcetype'] = 'osx_asl'


full_props['generic_single_line'] = {}

full_props['generic_single_line']['TIME_FORMAT'] = '%Y-%m-%dT%H:%M:%S.%3N %Z'

full_props['generic_single_line']['pulldown_type'] = '1'

full_props['generic_single_line']['SHOULD_LINEMERGE'] = 'false'

full_props['generic_single_line']['category'] = 'Miscellaneous'

full_props['generic_single_line']['description'] = 'A common log format with a predefined timestamp. Customize timestamp in "Timestamp" options'


full_props['source::.../var/log/secure.log(.\\d+)?'] = {}

full_props['source::.../var/log/secure.log(.\\d+)?']['sourcetype'] = 'osx_secure'


full_props['splunkd_conf'] = {}

full_props['splunkd_conf']['TIME_FORMAT'] = '%m-%d-%Y %H:%M:%S.%l %z'

full_props['splunkd_conf']['KV_MODE'] = 'none'

full_props['splunkd_conf']['SHOULD_LINEMERGE'] = 'false'

full_props['splunkd_conf']['TIMESTAMP_FIELDS'] = 'datetime'

full_props['splunkd_conf']['INDEXED_EXTRACTIONS'] = 'json'


full_props['source::.../var/log/splunk/splunkd_stderr.log'] = {}

full_props['source::.../var/log/splunk/splunkd_stderr.log']['sourcetype'] = 'splunkd_stderr'


full_props['splunk_web_service'] = {}

full_props['splunk_web_service']['MAX_TIMESTAMP_LOOKAHEAD'] = '40'

full_props['splunk_web_service']['namegroup-REPORT'] = ''

full_props['splunk_web_service']['REPORT-fields'] = '(?i)^(?:[^ ]* ){2}(?P<log_level>[^\\s]*)\\s+\\[(?P<requestid>\\w+)]\\s+(?P<component>[^ ]+):(?P<line>\\d+) - (?P<message>.+)'


full_props['source::....tar(.\\d+)?'] = {}

full_props['source::....tar(.\\d+)?']['unarchive_cmd'] = '_auto'

full_props['source::....tar(.\\d+)?']['sourcetype'] = 'preprocess-tar'

full_props['source::....tar(.\\d+)?']['NO_BINARY_CHECK'] = 'true'


full_props['osx_asl'] = {}

full_props['osx_asl']['namegroup-REPORT'] = ''

full_props['osx_asl']['REPORT-asl'] = '(?:\\[(\\S+) (.*?)\\])'

full_props['osx_asl']['BREAK_ONLY_BEFORE_DATE'] = 'False'


full_props['source::.../splunkd_access.log(.\\d+)?'] = {}

full_props['source::.../splunkd_access.log(.\\d+)?']['sourcetype'] = 'splunkd_access'


full_props['delayedrule::syslog'] = {}

full_props['delayedrule::syslog']['MORE_THAN_80'] = '^\\w{3} +\\d+ \\d\\d:\\d\\d:\\d\\d (?!AM|PM)[\\w\\-.]+ [\\w\\-/.]+(\\[\\d+\\])?:'

full_props['delayedrule::syslog']['sourcetype'] = 'syslog'


full_props['source::.../(apache|httpd).../error*'] = {}

full_props['source::.../(apache|httpd).../error*']['sourcetype'] = 'apache_error'


full_props['ruby_on_rails'] = {}

full_props['ruby_on_rails']['category'] = 'Application'

full_props['ruby_on_rails']['description'] = 'Output produced by a Ruby On Rails Web application framework'

full_props['ruby_on_rails']['BREAK_ONLY_BEFORE'] = 'Processing'

full_props['ruby_on_rails']['TIME_FORMAT'] = '%Y-%m-%d %H:%M:%S %Z'

full_props['ruby_on_rails']['pulldown_type'] = '1'

full_props['ruby_on_rails']['TIME_PREFIX'] = '(for [\\d\\.]+ at\\s)'


full_props['source::.../var/log/splunk/conf.log(.\\d+)?'] = {}

full_props['source::.../var/log/splunk/conf.log(.\\d+)?']['sourcetype'] = 'splunkd_conf'


full_props['sendmail_syslog'] = {}

full_props['sendmail_syslog']['category'] = 'Email'

full_props['sendmail_syslog']['description'] = 'Output produced by the Sendmail email server'

full_props['sendmail_syslog']['TIME_FORMAT'] = '%b %d %H:%M:%S'

full_props['sendmail_syslog']['pulldown_type'] = '1'

full_props['sendmail_syslog']['namegroup-REPORT'] = ''

full_props['sendmail_syslog']['TRANSFORMS'] = '(?::\\d\\d\\s+(?:\\d+\\s+|(?:user|daemon|local.?)\\.\\w+\\s+)*\\[?(\\w[\\w\\.\\-]{2,})\\]?\\s)'

full_props['sendmail_syslog']['MAX_TIMESTAMP_LOOKAHEAD'] = '32'

full_props['sendmail_syslog']['REPORT-syslog'] = '(?:sendmail\\[(\\d+)\\]: (\\w+):)'

full_props['sendmail_syslog']['SHOULD_LINEMERGE'] = 'False'

full_props['sendmail_syslog']['namegroup-TRANSFORMS'] = ''


full_props['source::.../var/log/cups/error_log(.\\d+)?'] = {}

full_props['source::.../var/log/cups/error_log(.\\d+)?']['sourcetype'] = 'cups_error'


full_props['django_error'] = {}

full_props['django_error']['MAX_TIMESTAMP_LOOKAHEAD'] = '40'

full_props['django_error']['TRUNCATE'] = '100000'


full_props['source::....(css|htm|html|sgml|shtml|template)'] = {}

full_props['source::....(css|htm|html|sgml|shtml|template)']['sourcetype'] = 'web'


full_props['source::.../procmail(_|.)log'] = {}

full_props['source::.../procmail(_|.)log']['sourcetype'] = 'procmail'


full_props['osx_monthly'] = {}

full_props['osx_monthly']['BREAK_ONLY_BEFORE'] = '^(Sun|Mon|Tue|Wed|Thu|Fri|Sat)'


full_props['source::....(tbz|tbz2)(.\\d+)?'] = {}

full_props['source::....(tbz|tbz2)(.\\d+)?']['unarchive_cmd'] = '_auto'

full_props['source::....(tbz|tbz2)(.\\d+)?']['sourcetype'] = 'preprocess-bzip'

full_props['source::....(tbz|tbz2)(.\\d+)?']['NO_BINARY_CHECK'] = 'true'


full_props['source::.../var/log/splunk/(web|report)_access(-\\d+)?.log(.\\d+)?'] = {}

full_props['source::.../var/log/splunk/(web|report)_access(-\\d+)?.log(.\\d+)?']['sourcetype'] = 'splunk_web_access'


full_props['log4php'] = {}

full_props['log4php']['category'] = 'Application'

full_props['log4php']['pulldown_type'] = 'true'

full_props['log4php']['description'] = 'Output produced by a machine that runs the log4php logging utility'

full_props['log4php']['BREAK_ONLY_BEFORE'] = '^\\w{3} \\w{3}'


full_props['known_binary'] = {}

full_props['known_binary']['invalid_cause'] = 'binary'

full_props['known_binary']['is_valid'] = 'False'

full_props['known_binary']['LEARN_MODEL'] = 'false'


full_props['source::.../var/log/rpmpkgs(.\\d+)?'] = {}

full_props['source::.../var/log/rpmpkgs(.\\d+)?']['sourcetype'] = 'rpmpkgs'


full_props['source::.../var/log/anaconda.syslog(.\\d+)?'] = {}

full_props['source::.../var/log/anaconda.syslog(.\\d+)?']['sourcetype'] = 'anaconda_syslog'


full_props['source::.../kvstore.log(.\\d+)?'] = {}

full_props['source::.../kvstore.log(.\\d+)?']['sourcetype'] = 'kvstore'


full_props['source::....Z(.\\d+)?'] = {}

full_props['source::....Z(.\\d+)?']['unarchive_cmd'] = 'gzip -cd -'

full_props['source::....Z(.\\d+)?']['sourcetype'] = 'preprocess-Z'

full_props['source::....Z(.\\d+)?']['NO_BINARY_CHECK'] = 'true'


full_props['source::.../var/log/splunk/django_access.log(.\\d+)?'] = {}

full_props['source::.../var/log/splunk/django_access.log(.\\d+)?']['sourcetype'] = 'django_access'


full_props['source::.../private/var/log/windowserver.log(.\\d+)?'] = {}

full_props['source::.../private/var/log/windowserver.log(.\\d+)?']['sourcetype'] = 'osx_window_server'


full_props['source::.../disk_objects.log(.\\d+)?'] = {}

full_props['source::.../disk_objects.log(.\\d+)?']['sourcetype'] = 'splunk_disk_objects'


full_props['source::.../var/log/daily.out(.\\d+)?'] = {}

full_props['source::.../var/log/daily.out(.\\d+)?']['sourcetype'] = 'osx_daily'


full_props['tsv'] = {}

full_props['tsv']['KV_MODE'] = 'none'

full_props['tsv']['category'] = 'Structured'

full_props['tsv']['description'] = 'Tab-separated value format. Set header and other settings in "Delimited Settings"'

full_props['tsv']['FIELD_DELIMITER'] = 'tab'

full_props['tsv']['INDEXED_EXTRACTIONS'] = 'tsv'

full_props['tsv']['pulldown_type'] = 'true'

full_props['tsv']['SHOULD_LINEMERGE'] = 'False'

full_props['tsv']['HEADER_FIELD_DELIMITER'] = 'tab'


full_props['source::.../private/var/log/mail.log(.\\d+)?'] = {}

full_props['source::.../private/var/log/mail.log(.\\d+)?']['sourcetype'] = 'syslog'


full_props['cisco_syslog'] = {}

full_props['cisco_syslog']['TIME_FORMAT'] = '%b %d %H:%M:%S'

full_props['cisco_syslog']['pulldown_type'] = '0'

full_props['cisco_syslog']['namegroup-REPORT'] = ''

full_props['cisco_syslog']['TRANSFORMS'] = '(?::\\d\\d\\s+(?:\\d+\\s+|(?:user|daemon|local.?)\\.\\w+\\s+)*\\[?(\\w[\\w\\.\\-]{2,})\\]?\\s)'

full_props['cisco_syslog']['MAX_TIMESTAMP_LOOKAHEAD'] = '32'

full_props['cisco_syslog']['REPORT-syslog'] = '(?:\\s([^\\s\\[]+)(?:\\[(\\d+)\\])?:\\s)'

full_props['cisco_syslog']['SHOULD_LINEMERGE'] = 'False'

full_props['cisco_syslog']['namegroup-TRANSFORMS'] = ''


full_props['source::.../splunkd_ui_access.log(.\\d+)?'] = {}

full_props['source::.../splunkd_ui_access.log(.\\d+)?']['sourcetype'] = 'splunkd_ui_access'


full_props['source::....csv'] = {}

full_props['source::....csv']['sourcetype'] = 'csv'


full_props['rule::access_combined'] = {}

full_props['rule::access_combined']['sourcetype'] = 'access_combined'

full_props['rule::access_combined']['MORE_THAN_75'] = '^\\S+ \\S+ \\S+ \\S* ?\\[[^\\]]+\\] "[^"]*" \\S+ \\S+ \\S+ "[^"]*"$'


full_props['source::.../var/log/crashreporter.log(.\\d+)?'] = {}

full_props['source::.../var/log/crashreporter.log(.\\d+)?']['sourcetype'] = 'osx_crashreporter'


full_props['rule::access_combined_wcookie'] = {}

full_props['rule::access_combined_wcookie']['sourcetype'] = 'access_combined_wcookie'

full_props['rule::access_combined_wcookie']['MORE_THAN_75'] = '^\\S+ \\S+ \\S+ \\S* ?\\[[^\\]]+\\] "[^"]*" \\S+ \\S+(?: \\S+)? "[^"]*" "[^"]*"'


full_props['default'] = {}

full_props['default']['TRUNCATE'] = '10000'

full_props['default']['CHARSET'] = 'UTF-8'

full_props['default']['MUST_BREAK_AFTER'] = ''

full_props['default']['BREAK_ONLY_BEFORE'] = ''

full_props['default']['MAX_DAYS_HENCE'] = '2'

full_props['default']['MAX_TIMESTAMP_LOOKAHEAD'] = '128'

full_props['default']['LEARN_SOURCETYPE'] = 'true'

full_props['default']['AUTO_KV_JSON'] = 'true'

full_props['default']['maxDist'] = '100'

full_props['default']['MAX_DIFF_SECS_HENCE'] = '604800'

full_props['default']['ANNOTATE_PUNCT'] = 'True'

full_props['default']['sourcetype'] = ''

full_props['default']['SEGMENTATION-inner'] = 'inner'

full_props['default']['priority'] = ''

full_props['default']['SHOULD_LINEMERGE'] = 'True'

full_props['default']['MAX_DIFF_SECS_AGO'] = '3600'

full_props['default']['SEGMENTATION'] = 'indexing'

full_props['default']['MUST_NOT_BREAK_BEFORE'] = ''

full_props['default']['HEADER_MODE'] = ''

full_props['default']['BREAK_ONLY_BEFORE_DATE'] = 'True'

full_props['default']['SEGMENTATION-standard'] = 'standard'

full_props['default']['LINE_BREAKER_LOOKBEHIND'] = '100'

full_props['default']['TRANSFORMS'] = ''

full_props['default']['DATETIME_CONFIG'] = '/etc/datetime.xml'

full_props['default']['SEGMENTATION-raw'] = 'none'

full_props['default']['SEGMENTATION-all'] = 'full'

full_props['default']['detect_trailing_nulls'] = 'false'

full_props['default']['MUST_NOT_BREAK_AFTER'] = ''

full_props['default']['MAX_DAYS_AGO'] = '2000'

full_props['default']['MAX_EVENTS'] = '256'

full_props['default']['SEGMENTATION-outer'] = 'outer'


full_props['PerformanceMonitor'] = {}

full_props['PerformanceMonitor']['namegroup-REPORT'] = ''

full_props['PerformanceMonitor']['SHOULD_LINEMERGE'] = 'false'

full_props['PerformanceMonitor']['LINE_BREAKER'] = '([\\r\\n]+---splunk-perfmon-end-of-event---\\r\\n[\\r\\n]*)'

full_props['PerformanceMonitor']['REPORT-MESSAGE'] = ''


full_props['source::....bz2?(.\\d+)?'] = {}

full_props['source::....bz2?(.\\d+)?']['unarchive_cmd'] = 'bzip2 -cd -'

full_props['source::....bz2?(.\\d+)?']['sourcetype'] = 'preprocess-bzip'

full_props['source::....bz2?(.\\d+)?']['NO_BINARY_CHECK'] = 'true'


full_props['source::.../var/log/spooler(.\\d+)?'] = {}

full_props['source::.../var/log/spooler(.\\d+)?']['sourcetype'] = 'spooler'


full_props['rule::snort'] = {}

full_props['rule::snort']['MORE_THAN_1'] = '(=\\+)+'

full_props['rule::snort']['sourcetype'] = 'snort'

full_props['rule::snort']['MORE_THAN_10'] = '(?:[0-9A-F]{2} ){16}'


full_props['source::.../var/log/secure(.\\d+)?'] = {}

full_props['source::.../var/log/secure(.\\d+)?']['sourcetype'] = 'linux_secure'


full_props['preprocess-tar'] = {}

full_props['preprocess-tar']['invalid_cause'] = 'archive'

full_props['preprocess-tar']['is_valid'] = 'False'

full_props['preprocess-tar']['LEARN_MODEL'] = 'false'


full_props['source::.../var/log/splunk/btool.log(.\\d+)?'] = {}

full_props['source::.../var/log/splunk/btool.log(.\\d+)?']['sourcetype'] = 'splunk_btool'


full_props['postfix_syslog'] = {}

full_props['postfix_syslog']['category'] = 'Email'

full_props['postfix_syslog']['description'] = 'Output produced by the Postfix email server'

full_props['postfix_syslog']['TRANSFORMS-host'] = '(?::\\d\\d\\s+(?:\\d+\\s+|(?:user|daemon|local.?)\\.\\w+\\s+)*\\[?(\\w[\\w\\.\\-]{2,})\\]?\\s)'

full_props['postfix_syslog']['TIME_FORMAT'] = '%b %d %H:%M:%S'

full_props['postfix_syslog']['pulldown_type'] = '1'

full_props['postfix_syslog']['namegroup-REPORT'] = ''

full_props['postfix_syslog']['MAX_TIMESTAMP_LOOKAHEAD'] = '32'

full_props['postfix_syslog']['REPORT-syslog'] = '(?:\\s([^\\s\\[]+)(?:\\[(\\d+)\\])?:\\s)'

full_props['postfix_syslog']['SHOULD_LINEMERGE'] = 'False'

full_props['postfix_syslog']['namegroup-TRANSFORMS'] = ''


full_props['lastlog'] = {}

full_props['lastlog']['invalid_cause'] = 'binary'

full_props['lastlog']['LEARN_MODEL'] = 'false'


full_props['mysqld_bin'] = {}

full_props['mysqld_bin']['category'] = 'Database'

full_props['mysqld_bin']['pulldown_type'] = '1'

full_props['mysqld_bin']['BREAK_ONLY_BEFORE'] = '^#\\d{6}'

full_props['mysqld_bin']['description'] = 'Binary log output produced by the MySQL database server'

full_props['mysqld_bin']['maxDist'] = '20'


full_props['WinRegistry'] = {}

full_props['WinRegistry']['LINE_BREAKER'] = '([\\r\\n]+---splunk-regmon-end-of-event---\\r\\n[\\r\\n]*)'

full_props['WinRegistry']['DATETIME_CONFIG'] = 'NONE'


full_props['splunk_help'] = {}

full_props['splunk_help']['MAX_EVENTS'] = '200000'

full_props['splunk_help']['BREAK_ONLY_BEFORE'] = 'gooblygook'

full_props['splunk_help']['namegroup-TRANSFORMS'] = ''

full_props['splunk_help']['TRANSFORMS-help'] = '(?:.)'


full_props['preprocess-targz'] = {}

full_props['preprocess-targz']['invalid_cause'] = 'archive'

full_props['preprocess-targz']['is_valid'] = 'False'

full_props['preprocess-targz']['LEARN_MODEL'] = 'false'


full_props['osx_window_server'] = {}

full_props['osx_window_server']['SHOULD_LINEMERGE'] = 'False'


full_props['rule::postfix_syslog'] = {}

full_props['rule::postfix_syslog']['sourcetype'] = 'postfix_syslog'

full_props['rule::postfix_syslog']['MORE_THAN_75'] = '^\\w{3} +\\d+ \\d\\d:\\d\\d:\\d\\d .* postfix(/\\w+)?\\[\\d+\\]:'


full_props['splunk_web_access'] = {}

full_props['splunk_web_access']['maxDist'] = '28'

full_props['splunk_web_access']['REPORT-access'] = '(?:^(?<clientip>(?:\\S+))\\s++(?<ident>(?:\\S+))\\s++(?<user>(?:\\S+))\\s++(?<req_time>(?:\\[(?:[^\\]]*+)\\]))\\s++(?:"\\s*+(?<method>(?:[^\\s"]++))?(?:\\s++(?<uri>(?<uri_>(?<domain0>\\w++:\\/\\/[^\\/\\s"]++))?+(?<uri_path>(?:\\/++(?<root>(?:\\\\"|[^\\s\\?\\/"])++)\\/++)?(?:(?:\\\\"|[^\\s\\?\\/"])*+\\/++)*(?<file>[^\\s\\?\\/]+)?)(?:\\?(?<uri_query>[^\\s]*))?)(?:\\s++(?<version>(?:[^\\s"]++)))*)?\\s*+")\\s++(?<status>(?:\\S+))\\s++(?<bytes>(?:\\S+))(?:\\s++"(?<referer>(?<referer_>(?<domain>\\w++:\\/\\/[^\\/\\s"]++))?+[^"]*+)"(?:\\s++(?<useragent>(?:"(?:[^"]*+)"))(?:\\s++(?<cookie>(?:"(?:[^"]*+)")))?+)?+)?(?<other>(?:.*)))'

full_props['splunk_web_access']['EXTRACT-extract_spent'] = '(?<spent>\\d+)ms$'

full_props['splunk_web_access']['namegroup-REPORT'] = 'clientip,ident,user,req_time,method,uri,uri_,domain0,uri_path,root,file,uri_query,version,status,bytes,referer,referer_,domain,useragent,cookie,other'

full_props['splunk_web_access']['MAX_TIMESTAMP_LOOKAHEAD'] = '128'

full_props['splunk_web_access']['TIME_PREFIX'] = '\\['

full_props['splunk_web_access']['SHOULD_LINEMERGE'] = 'False'


full_props['source::.../messages(.\\d+)?'] = {}

full_props['source::.../messages(.\\d+)?']['sourcetype'] = 'syslog'


full_props['sar'] = {}

full_props['sar']['MAX_EVENTS'] = '1000'

full_props['sar']['BREAK_ONLY_BEFORE'] = '(?:^\\s*$)|00:00:0|/s|%|[a-z]-'


full_props['WinPrintMon'] = {}

full_props['WinPrintMon']['SHOULD_LINEMERGE'] = 'false'

full_props['WinPrintMon']['DATETIME_CONFIG'] = 'NONE'


full_props['kvstore'] = {}

full_props['kvstore']['KV_MODE'] = 'none'

full_props['kvstore']['TRUNCATE'] = '1000000'

full_props['kvstore']['TIMESTAMP_FIELDS'] = 'datetime'

full_props['kvstore']['INDEXED_EXTRACTIONS'] = 'json'

full_props['kvstore']['TIME_FORMAT'] = '%m-%d-%Y %H:%M:%S.%l %z'

full_props['kvstore']['SHOULD_LINEMERGE'] = 'false'


full_props['source::....crash.log(.\\d+)?'] = {}

full_props['source::....crash.log(.\\d+)?']['sourcetype'] = 'osx_crash_log'


full_props['iis'] = {}

full_props['iis']['category'] = 'Web'

full_props['iis']['description'] = 'W3C Extended log format produced by the Microsoft Internet Information Services (IIS) web server'

full_props['iis']['detect_trailing_nulls'] = 'auto'

full_props['iis']['INDEXED_EXTRACTIONS'] = 'w3c'

full_props['iis']['pulldown_type'] = 'true'

full_props['iis']['MAX_TIMESTAMP_LOOKAHEAD'] = '32'

full_props['iis']['SHOULD_LINEMERGE'] = 'False'


full_props['osx_daily'] = {}

full_props['osx_daily']['BREAK_ONLY_BEFORE'] = '^(Sun|Mon|Tue|Wed|Thu|Fri|Sat)'


full_props['ssl_error'] = {}

full_props['ssl_error']['pulldown_type'] = '0'

full_props['ssl_error']['BREAK_ONLY_BEFORE_DATE'] = 'False'


full_props['cups_error'] = {}

full_props['cups_error']['BREAK_ONLY_BEFORE_DATE'] = 'False'


full_props['source::.../man/man\\d+/*.\\d+'] = {}

full_props['source::.../man/man\\d+/*.\\d+']['sourcetype'] = 'manpage'


full_props['splunk_com_php_error'] = {}

full_props['splunk_com_php_error']['maxDist'] = '70'

full_props['splunk_com_php_error']['MAX_TIMESTAMP_LOOKAHEAD'] = '40'


full_props['source::....(tar.gz|tgz)(.\\d+)?'] = {}

full_props['source::....(tar.gz|tgz)(.\\d+)?']['unarchive_cmd'] = '_auto'

full_props['source::....(tar.gz|tgz)(.\\d+)?']['sourcetype'] = 'preprocess-targz'

full_props['source::....(tar.gz|tgz)(.\\d+)?']['NO_BINARY_CHECK'] = 'true'


full_props['source::....(jar)(.\\d+)?'] = {}

full_props['source::....(jar)(.\\d+)?']['sourcetype'] = 'source_archive'


full_props['cisco_cdr'] = {}

full_props['cisco_cdr']['maxDist'] = '1'

full_props['cisco_cdr']['SHOULD_LINEMERGE'] = 'False'


full_props['csv'] = {}

full_props['csv']['KV_MODE'] = 'none'

full_props['csv']['category'] = 'Structured'

full_props['csv']['description'] = 'Comma-separated value format. Set header and other settings in "Delimited Settings"'

full_props['csv']['INDEXED_EXTRACTIONS'] = 'csv'

full_props['csv']['pulldown_type'] = 'true'

full_props['csv']['SHOULD_LINEMERGE'] = 'False'


full_props['log4j'] = {}

full_props['log4j']['category'] = 'Application'

full_props['log4j']['BREAK_ONLY_BEFORE'] = '\\d\\d?:\\d\\d:\\d\\d'

full_props['log4j']['description'] = 'Output produced by any Java 2 Enterprise Edition (J2EE) application server using log4j'

full_props['log4j']['maxDist'] = '75'

full_props['log4j']['pulldown_type'] = 'true'


full_props['source::.../var/log/wtmp(.\\d+)?'] = {}

full_props['source::.../var/log/wtmp(.\\d+)?']['sourcetype'] = 'wtmp'


full_props['WinNetMonMk'] = {}

full_props['WinNetMonMk']['KV_MODE'] = 'multi_WinNetMonMk'

full_props['WinNetMonMk']['pulldown_type'] = '0'

full_props['WinNetMonMk']['NO_BINARY_CHECK'] = '1'


full_props['misc_text'] = {}

full_props['misc_text']['LEARN_MODEL'] = 'false'

full_props['misc_text']['pulldown_type'] = 'false'

full_props['misc_text']['CHECK_METHOD'] = 'modtime'

full_props['misc_text']['BREAK_ONLY_BEFORE'] = 'goblygook'

full_props['misc_text']['DATETIME_CONFIG'] = 'NONE'

full_props['misc_text']['MAX_EVENTS'] = '200000'


full_props['splunk_directory_monitor_misc'] = {}

full_props['splunk_directory_monitor_misc']['MAX_TIMESTAMP_LOOKAHEAD'] = '40'


full_props['websphere_trlog'] = {}

full_props['websphere_trlog']['category'] = 'Application'

full_props['websphere_trlog']['pulldown_type'] = 'true'

full_props['websphere_trlog']['namegroup-REPORT'] = ''

full_props['websphere_trlog']['description'] = 'Trace output produced by the IBM WebSphere application server'

full_props['websphere_trlog']['REPORT-st'] = '(?:] ([a-fA-F0-9]{8}))'


full_props['asterisk_event'] = {}

full_props['asterisk_event']['maxDist'] = '3'

full_props['asterisk_event']['SHOULD_LINEMERGE'] = 'False'


full_props['splunkd'] = {}

full_props['splunkd']['TIME_FORMAT'] = '%m-%d-%Y %H:%M:%S.%l %z'

full_props['splunkd']['MAX_TIMESTAMP_LOOKAHEAD'] = '40'

full_props['splunkd']['SHOULD_LINEMERGE'] = 'false'


full_props['splunkd_remote_searches'] = {}

full_props['splunkd_remote_searches']['TIME_FORMAT'] = '%m-%d-%Y %H:%M:%S.%l %z'

full_props['splunkd_remote_searches']['MAX_TIMESTAMP_LOOKAHEAD'] = '40'

full_props['splunkd_remote_searches']['SHOULD_LINEMERGE'] = 'false'


full_props['source::.../var/log/splunk/*crash-*.log'] = {}

full_props['source::.../var/log/splunk/*crash-*.log']['sourcetype'] = 'splunkd_crash_log'


full_props['ignored_type'] = {}

full_props['ignored_type']['invalid_cause'] = 'ignored_type'

full_props['ignored_type']['is_valid'] = 'False'

full_props['ignored_type']['LEARN_MODEL'] = 'false'


full_props['source::.../var/log/lastlog(.\\d+)?'] = {}

full_props['source::.../var/log/lastlog(.\\d+)?']['sourcetype'] = 'lastlog'


full_props['source::.../var/log/splunk/metrics.log(.\\d+)?'] = {}

full_props['source::.../var/log/splunk/metrics.log(.\\d+)?']['sourcetype'] = 'splunkd'


full_props['source::.../var/log/splunk/splunk_stdout.log'] = {}

full_props['source::.../var/log/splunk/splunk_stdout.log']['sourcetype'] = 'splunkd_stdout'


full_props['osx_install'] = {}

full_props['osx_install']['BREAK_ONLY_BEFORE_DATE'] = 'False'


full_props['dmesg'] = {}

full_props['dmesg']['category'] = 'Operating System'

full_props['dmesg']['pulldown_type'] = '1'

full_props['dmesg']['DATETIME_CONFIG'] = 'NONE'

full_props['dmesg']['description'] = 'Output produced by the "dmesg" *nix command, printing the *nix kernel ring buffer'

full_props['dmesg']['BREAK_ONLY_BEFORE'] = '^\\S'


full_props['source::.../var/log/splunk/splunkd-utility.log(.\\d+)?'] = {}

full_props['source::.../var/log/splunk/splunkd-utility.log(.\\d+)?']['sourcetype'] = 'splunkd'


full_props['osx_secure'] = {}

full_props['osx_secure']['BREAK_ONLY_BEFORE_DATE'] = 'False'


full_props['preprocess-zip'] = {}

full_props['preprocess-zip']['invalid_cause'] = 'archive'

full_props['preprocess-zip']['is_valid'] = 'False'

full_props['preprocess-zip']['LEARN_MODEL'] = 'false'


full_props['asterisk_queue'] = {}

full_props['asterisk_queue']['SHOULD_LINEMERGE'] = 'False'


full_props['stash'] = {}

full_props['stash']['KV_MODE'] = 'none'

full_props['stash']['MAX_DIFF_SECS_HENCE'] = '155520000'

full_props['stash']['LEARN_MODEL'] = 'false'

full_props['stash']['MAX_DAYS_HENCE'] = '2'

full_props['stash']['TRUNCATE'] = '0'

full_props['stash']['HEADER_MODE'] = 'firstline'

full_props['stash']['MAX_DAYS_AGO'] = '10000'

full_props['stash']['namegroup-REPORT'] = ''

full_props['stash']['MAX_TIMESTAMP_LOOKAHEAD'] = '64'

full_props['stash']['REPORT-1'] = ''

full_props['stash']['MAX_DIFF_SECS_AGO'] = '155520000'


full_props['rule::access_common'] = {}

full_props['rule::access_common']['sourcetype'] = 'access_common'

full_props['rule::access_common']['MORE_THAN_75'] = '^\\S+ \\S+ \\S+ \\[[^\\]]+\\] "[^"]+" \\S+ \\S+$'


full_props['source::.../(u_|)ex(tend|\\d{4,8})*?.log'] = {}

full_props['source::.../(u_|)ex(tend|\\d{4,8})*?.log']['sourcetype'] = 'iis'


full_props['source::...stash'] = {}

full_props['source::...stash']['sourcetype'] = 'stash'


full_props['source::.../var/log/ftp.log(.\\d+)?'] = {}

full_props['source::.../var/log/ftp.log(.\\d+)?']['sourcetype'] = 'ftp'


full_props['osx_weekly'] = {}

full_props['osx_weekly']['BREAK_ONLY_BEFORE'] = '^(Sun|Mon|Tue|Wed|Thu|Fri|Sat)'


full_props['source::....(?<!tar.)gz(.\\d+)?'] = {}

full_props['source::....(?<!tar.)gz(.\\d+)?']['unarchive_cmd'] = 'gzip -cd -'

full_props['source::....(?<!tar.)gz(.\\d+)?']['sourcetype'] = 'preprocess-gzip'

full_props['source::....(?<!tar.)gz(.\\d+)?']['NO_BINARY_CHECK'] = 'true'


full_props['rule::sendmail_syslog'] = {}

full_props['rule::sendmail_syslog']['sourcetype'] = 'sendmail_syslog'

full_props['rule::sendmail_syslog']['MORE_THAN_75'] = '^\\w{3} +\\d+ \\d\\d:\\d\\d:\\d\\d .* (sendmail|imapd|ipop3d)\\[\\d+\\]:'


full_props['spooler'] = {}

full_props['spooler']['BREAK_ONLY_BEFORE_DATE'] = 'False'


full_props['source::PerfmonMk...'] = {}

full_props['source::PerfmonMk...']['KV_MODE'] = 'multi_PerfmonMk'

full_props['source::PerfmonMk...']['pulldown_type'] = '1'

full_props['source::PerfmonMk...']['NO_BINARY_CHECK'] = '1'

full_props['source::PerfmonMk...']['EXTRACT-collection,category,object'] = 'collection=\\"?(?P<collection>[^\\"\\n]+)\\"?\\ncategory=\\"?(?P<category>[^\\"\\n]+)\\"?\\nobject=\\"?(?P<object>[^\\"\\n]+)\\"?\\n'



function string.starts(String,Start)
   return string.sub(String,1,string.len(Start))==Start
end

function generate_sourcetype_re( sourcetype,full_props)
    sourcetype_stanza = full_props[sourcetype]
    sourcetype_re = {}
    for k,v in pairs(sourcetype_stanza) do
        if string.starts(k,'REPORT') and k ~= '' then
            sourcetype_re[sourcetype_stanza['namegroup-REPORT']] = v
        end
        if string.starts(k,'TRANSFORMS') and k ~= '' then
            sourcetype_re[sourcetype_stanza['namegroup-TRANSFORMS']] = v
        end
    end
    return sourcetype_re
end

line = '113.96.151.228 - - [23/Mar/2015:15:07:30 +0800] "GET /drupal7/sites/default/files/css/css_tvjLXeiJa667A1Ha2T2SVo0fKFy5Eiy6QNovxfdLlpI.css HTTP/1.1" 200 4830 "http://221.176.36.22/drupal7/?q=comment/511" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36"'

function extract_event( sourcetype_re,line )
    namegroup = {}
    for k,v in pairs(sourcetype_re) do
        count = 0
        group={rex_pcre.new(v):match(line)}
        for w in string.gmatch(k,"([^',']+)") do
            count = count+1
            namegroup[w]=group[count]
        end
    end
    return namegroup
end

function print_table( t )
    for k,v in pairs(t) do
        print(k,v)
    end
end

sourcetype_re = generate_sourcetype_re( sourcetype,full_props)
local logfile = arg[1]
local f = io.open(logfile,'r')
assert(f)
print('===================lua script exec begin===================')
for line in f:lines() do
    namegroup = extract_event( sourcetype_re,line )
    print('=========namegroup begin=========')
    print_table(namegroup)
    print('=========namegroup end=========')
end
print('=====================lua script exec finish=======================')
